CREATE states (sid INT, sname STRING, sabbr STRING)
INSERT INTO states (1, 'Alabama', 'AL')
INSERT INTO states (2, 'Alaska', 'AK')
INSERT INTO states (3, 'Arizona', 'AZ')
INSERT INTO states (4, 'Arkansas', 'AR')
INSERT INTO states (5, 'California', 'CA')
INSERT INTO states (6, 'Colorado', 'CO')
INSERT INTO states (7, 'Connecticut', 'CT')
INSERT INTO states (8, 'Delaware', 'DE')
INSERT INTO states (9, 'Florida', 'FL')
INSERT INTO states (10, 'Georgia', 'GA')
INSERT INTO states (11, 'Hawaii', 'HI')
INSERT INTO states (12, 'Idaho', 'ID')
INSERT INTO states (13, 'Illinois', 'IL')
INSERT INTO states (14, 'Indiana', 'IN')
INSERT INTO states (15, 'Iowa', 'IA')
INSERT INTO states (16, 'Kansas', 'KS')
INSERT INTO states (17, 'Kentucky', 'KY')
INSERT INTO states (18, 'Louisiana', 'LA')
INSERT INTO states (19, 'Maine', 'ME')
INSERT INTO states (20, 'Maryland', 'MD')
INSERT INTO states (21, 'Massachusetts', 'MA')
INSERT INTO states (22, 'Michigan', 'MI')
INSERT INTO states (23, 'Minnesota', 'MN')
INSERT INTO states (24, 'Mississippi', 'MS')
INSERT INTO states (25, 'Missouri', 'MO')
INSERT INTO states (26, 'Montana', 'MT')
INSERT INTO states (27, 'Nebraska', 'NE')
INSERT INTO states (28, 'Nevada', 'NV')
INSERT INTO states (29, 'New Hampshire', 'NH')
INSERT INTO states (30, 'New Jersey', 'NJ')
INSERT INTO states (31, 'New Mexico', 'NM')
INSERT INTO states (32, 'New York', 'NY')
INSERT INTO states (33, 'North Carolina', 'NC')
INSERT INTO states (34, 'North Dakota', 'ND')
INSERT INTO states (35, 'Ohio', 'OH')
INSERT INTO states (36, 'Oklahoma', 'OK')
INSERT INTO states (37, 'Oregon', 'OR')
INSERT INTO states (38, 'Pennsylvania', 'PA')
INSERT INTO states (39, 'Rhode Island', 'RI')
INSERT INTO states (40, 'South Carolina', 'SC')
INSERT INTO states (41, 'South Dakota', 'SD')
INSERT INTO states (42, 'Tennessee', 'TN')
INSERT INTO states (43, 'Texas', 'TX')
INSERT INTO states (44, 'Utah', 'UT')
INSERT INTO states (45, 'Vermont', 'VT')
INSERT INTO states (46, 'Virginia', 'VA')
INSERT INTO states (47, 'Washington', 'WA')
INSERT INTO states (48, 'West Virginia', 'WV')
INSERT INTO states (49, 'Wisconsin', 'WI')
INSERT INTO states (50, 'Wyoming', 'WY')
EXIT
