CREATE airports1 (aid INT, astate STRING, acode STRING, aname STRING)
CREATE airports2 (aid INT, astate STRING, acode STRING, aname STRING)
INSERT INTO airports1 (110, 'AK', 'A61', 'Tuntutuliak Airport')
INSERT INTO airports1 (111, 'AK', 'UNK', 'Unalakleet Airport')
INSERT INTO airports1 (112, 'AK', 'DUT', 'Unalaska Airport')
INSERT INTO airports1 (113, 'AK', 'VDZ', 'Valdez Pioneer Field')
INSERT INTO airports1 (114, 'AK', 'AWI', 'Wainwright Airport')
INSERT INTO airports1 (115, 'AK', 'WRG', 'Wrangell Airport')
INSERT INTO airports1 (116, 'AK', 'YAK', 'Yakutat Airport')
INSERT INTO airports1 (117, 'AL', 'ANB', 'Anniston Municipal Airport')
INSERT INTO airports1 (118, 'AL', 'BHM', 'Birmingham International Airport')
INSERT INTO airports1 (119, 'AL', 'DHN', 'Dothan Regional Airport')
INSERT INTO airports1 (120, 'AL', 'HSV', 'Huntsville International Airport')
INSERT INTO airports1 (121, 'AL', 'MOB', 'Mobile Regional Airport')
INSERT INTO airports1 (122, 'AL', 'MGM', 'Montgomery Regional Airport')
INSERT INTO airports1 (123, 'AL', 'MSL', 'Northwest Alabama Regional Airport')
INSERT INTO airports1 (124, 'AL', 'ASN', 'Talladega Municipal Airport')
INSERT INTO airports1 (125, 'AL', 'TCL', 'Tuscaloosa Regional Airport')
INSERT INTO airports1 (126, 'AR', 'FYV', 'Drake Field')
INSERT INTO airports1 (127, 'AR', 'XNA', 'Northwest Arkansas Regional Airport')
INSERT INTO airports1 (128, 'AR', 'FSM', 'Fort Smith Airport')
INSERT INTO airports1 (129, 'AR', 'HRO', 'Boone County Airport')
INSERT INTO airports1 (130, 'AR', 'HOT', 'Memorial Field Airport')
INSERT INTO airports1 (131, 'AR', 'JBR', 'Jonesboro Municipal Airport')
INSERT INTO airports1 (132, 'AR', 'LIT', 'Little Rock National Airport')
INSERT INTO airports1 (133, 'AR', 'BPK', 'Baxter County Regional Airport')
INSERT INTO airports1 (134, 'AR', 'TXK', 'Texarkana Regional Airport')
INSERT INTO airports1 (135, 'AS', 'FAQ', 'Fitiuta Airport')
INSERT INTO airports1 (136, 'AS', 'Z08', 'Ofu Airport')
INSERT INTO airports1 (137, 'AS', 'PPG', 'Pago Pago International Airport')
INSERT INTO airports1 (138, 'AZ', 'IFP', 'Laughlin/Bullhead International Airport')
INSERT INTO airports1 (139, 'AZ', 'FLG', 'Flagstaff Pulliam Airport')
INSERT INTO airports1 (140, 'AZ', 'FHU', 'Sierra Vista Municipal Airport')
INSERT INTO airports1 (141, 'AZ', 'GYR', 'Phoenix Goodyear Airport')
INSERT INTO airports1 (142, 'AZ', 'GCN', 'Grand Canyon National Park Airport')
INSERT INTO airports1 (143, 'AZ', 'IGM', 'Kingman Airport')
INSERT INTO airports1 (144, 'AZ', 'HII', 'Lake Havasu City Airport')
EXIT
