INSERT INTO airports2 (1, 'AK', 'ADK', 'Adak Airport')
INSERT INTO airports2 (2, 'AK', 'AUK', 'Alakanuk Airport')
INSERT INTO airports2 (3, 'AK', 'AFM', 'Ambler Airport')
INSERT INTO airports2 (4, 'AK', 'AKP', 'Anaktuvuk Pass Airport')
INSERT INTO airports2 (5, 'AK', 'ANC', 'Anchorage International Airport')
INSERT INTO airports2 (6, 'AK', 'MRI', 'Merrill Field')
INSERT INTO airports2 (7, 'AK', 'LHD', 'Lake Hood Airport')
INSERT INTO airports2 (8, 'AK', 'AGN', 'Angoon Seaplane Base')
INSERT INTO airports2 (9, 'AK', 'ANI', 'Aniak Airport')
INSERT INTO airports2 (10, 'AK', 'ATK', 'Atqasuk Edward Burnell Sr Memorial Airport')
INSERT INTO airports2 (11, 'AK', 'BRW', 'Wiley Post-Will Rogers Memorial Airport')
INSERT INTO airports2 (12, 'AK', 'BET', 'Bethel Airport')
INSERT INTO airports2 (13, 'AK', 'BVK', 'Buckland Airport')
INSERT INTO airports2 (14, 'AK', 'CFK', 'Chefornak Airport')
INSERT INTO airports2 (15, 'AK', 'VAK', 'Chevak Airport')
INSERT INTO airports2 (16, 'AK', 'CDB', 'Cold Bay Airport')
INSERT INTO airports2 (17, 'AK', 'CDV', 'Cordova Municipal Airport')
INSERT INTO airports2 (18, 'AK', 'CGA', 'Craig Airport')
INSERT INTO airports2 (19, 'AK', 'SCC', 'Deadhorse Airport')
INSERT INTO airports2 (20, 'AK', 'BIG', 'Allen Aaf Airport')
INSERT INTO airports2 (21, 'AK', 'DLG', 'Dillingham Airport')
INSERT INTO airports2 (22, 'AK', 'EEK', 'Eek Airport')
INSERT INTO airports2 (23, 'AK', 'ELI', 'Elim Airport')
INSERT INTO airports2 (24, 'AK', 'ENM', 'Emmonak Airport')
INSERT INTO airports2 (25, 'AK', 'KEB', 'English Bay Airport')
INSERT INTO airports2 (26, 'AK', 'FAI', 'Fairbanks International Airport')
INSERT INTO airports2 (27, 'AK', 'FYU', 'Fort Yukon Airport')
INSERT INTO airports2 (28, 'AK', 'GBH', 'Galbraith Lake Airport')
INSERT INTO airports2 (29, 'AK', 'GAL', 'Edward G. Pitka Sr Airport')
INSERT INTO airports2 (30, 'AK', 'GAM', 'Gambell Airport')
INSERT INTO airports2 (31, 'AK', 'N93', 'Golovin Airport')
INSERT INTO airports2 (32, 'AK', 'GKN', 'Gulkana Airport')
INSERT INTO airports2 (33, 'AK', 'GST', 'Gustavus Airport')
INSERT INTO airports2 (34, 'AK', 'HNS', 'Haines Airport')
INSERT INTO airports2 (35, 'AK', 'HYL', 'Hollis Seaplane Base')
INSERT INTO airports2 (36, 'AK', 'HOM', 'Homer Airport')
INSERT INTO airports2 (37, 'AK', 'HNH', 'Hoonah Airport')
INSERT INTO airports2 (38, 'AK', 'HPB', 'Hooper Bay Airport')
INSERT INTO airports2 (39, 'AK', 'HLA', 'Huslia Airport')
INSERT INTO airports2 (40, 'AK', 'HSL', 'Huslia Airport')
INSERT INTO airports2 (41, 'AK', 'ILI', 'Iliamna Airport')
INSERT INTO airports2 (42, 'AK', 'JNU', 'Juneau International Airport')
INSERT INTO airports2 (43, 'AK', 'KAE', 'Kake Airport')
INSERT INTO airports2 (44, 'AK', 'BTI', 'Barter Island LRRS Airport')
INSERT INTO airports2 (45, 'AK', 'KLG', 'Kalskag Airport')
INSERT INTO airports2 (46, 'AK', 'KAL', 'Kaltag Airport')
INSERT INTO airports2 (47, 'AK', 'Z09', 'Kasigluk Airport')
INSERT INTO airports2 (48, 'AK', 'ENA', 'Kenai Municipal Airport')
INSERT INTO airports2 (49, 'AK', 'KTN', 'Ketchikan International Airport')
INSERT INTO airports2 (50, 'AK', 'IAN', 'Bob Baker Memorial Airport')
INSERT INTO airports2 (51, 'AK', 'KVC', 'King Cove Airport')
INSERT INTO airports2 (52, 'AK', 'AKN', 'King Salmon Airport')
INSERT INTO airports2 (53, 'AK', 'IIK', 'Kipnuk Airport')
INSERT INTO airports2 (54, 'AK', 'KVL', 'Kivalina Airport')
INSERT INTO airports2 (55, 'AK', 'AKW', 'Klawock Airport')
INSERT INTO airports2 (56, 'AK', 'ADQ', 'Kodiak Airport')
INSERT INTO airports2 (57, 'AK', 'KDK', 'Kodiak Municipal Airport')
INSERT INTO airports2 (58, 'AK', 'T44', 'Trident Basin Seaplane Base')
INSERT INTO airports2 (59, 'AK', 'DUY', 'Kongiganak Airport')
INSERT INTO airports2 (60, 'AK', '2A9', 'Kotlik Airport')
INSERT INTO airports2 (61, 'AK', 'OTZ', 'Ralph Wien Memorial Airport')
INSERT INTO airports2 (62, 'AK', 'KKA', 'Koyuk Airport')
INSERT INTO airports2 (63, 'AK', 'KWT', 'Kwethluk Airport')
INSERT INTO airports2 (64, 'AK', 'GGV', 'Kwigillingok Airport')
INSERT INTO airports2 (65, 'AK', 'A85', 'Kwigillingok Airport')
INSERT INTO airports2 (66, 'AK', '2A3', 'Larsen Bay Airport')
INSERT INTO airports2 (67, 'AK', 'MBA', 'Manokotak Airport')
INSERT INTO airports2 (68, 'AK', 'MDM', 'Marshall Don Hunter Sr Airport')
INSERT INTO airports2 (69, 'AK', '3A5', 'Marshall Don Hunter Sr')
INSERT INTO airports2 (70, 'AK', 'MLL', 'Marshall Airport')
INSERT INTO airports2 (71, 'AK', 'MCG', 'McGrath Airport')
INSERT INTO airports2 (72, 'AK', 'MTM', 'Metlakatla Airport')
INSERT INTO airports2 (73, 'AK', 'MOU', 'Mountain Village Airport')
INSERT INTO airports2 (74, 'AK', 'WNA', 'Napakiak Airport')
INSERT INTO airports2 (75, 'AK', 'EWU', 'Newtok Airport')
INSERT INTO airports2 (76, 'AK', 'WTK', 'Noatak Airport')
INSERT INTO airports2 (77, 'AK', 'OME', 'Nome Airport')
INSERT INTO airports2 (78, 'AK', 'D76', 'Robert (Bob) Curtis Memorial Airport')
INSERT INTO airports2 (79, 'AK', 'ORV', 'Robert (Bob) Curtis Memorial Airport')
INSERT INTO airports2 (80, 'AK', 'AQT', 'Nuiqsut Airport')
INSERT INTO airports2 (81, 'AK', 'NUL', 'Nulato Airport')
INSERT INTO airports2 (82, 'AK', '16A', 'Nunapitchuk Airport')
INSERT INTO airports2 (83, 'AK', '6R7', 'Old Harbor Airport')
INSERT INTO airports2 (84, 'AK', 'PSG', 'Petersburg Airport')
INSERT INTO airports2 (85, 'AK', '0AK', 'Pilot Station Airport')
INSERT INTO airports2 (86, 'AK', 'PHO', 'Point Hope Airport')
INSERT INTO airports2 (87, 'AK', 'PGM', 'Port Graham Airport')
INSERT INTO airports2 (88, 'AK', 'PTH', 'Port Heiden Airport')
INSERT INTO airports2 (89, 'AK', 'ORI', 'Port Lions Airport')
INSERT INTO airports2 (90, 'AK', 'PPC', 'Prospect Creek Airport')
INSERT INTO airports2 (91, 'AK', 'AQH', 'Quinhagak Airport')
INSERT INTO airports2 (92, 'AK', 'RSH', 'Russian Mission Airport')
INSERT INTO airports2 (93, 'AK', 'SDP', 'Sand Point Airport')
INSERT INTO airports2 (94, 'AK', 'SVA', 'Savoonga Airport')
INSERT INTO airports2 (95, 'AK', 'SCM', 'Scammon Bay Airport')
INSERT INTO airports2 (96, 'AK', 'WLK', 'Selawik Airport')
INSERT INTO airports2 (97, 'AK', 'SOV', 'Seldovia Airport')
INSERT INTO airports2 (98, 'AK', 'SHH', 'Shishmaref Airport')
INSERT INTO airports2 (99, 'AK', 'SHG', 'Shungnak Airport')
INSERT INTO airports2 (100, 'AK', 'SIT', 'Sitka Rocky Gutierrez Airport')
INSERT INTO airports2 (101, 'AK', 'SGY', 'Skagway Airport')
INSERT INTO airports2 (102, 'AK', 'KSM', 'St Marys Airport')
INSERT INTO airports2 (103, 'AK', 'SNP', 'Saint Paul Island Airport')
INSERT INTO airports2 (104, 'AK', 'WBB', 'Stebbins Airport')
INSERT INTO airports2 (105, 'AK', 'TAL', 'Ralph M Calhoun Memorial Airport')
INSERT INTO airports2 (106, 'AK', 'KTB', 'Thorne Bay Airport')
INSERT INTO airports2 (107, 'AK', 'TOG', 'Togiak Airport')
INSERT INTO airports2 (108, 'AK', 'OOK', 'Toksook Bay Airport')
INSERT INTO airports2 (109, 'AK', 'TLT', 'Tuluksak Airport')
INSERT INTO airports2 (110, 'AK', 'A61', 'Tuntutuliak Airport')
INSERT INTO airports2 (111, 'AK', 'UNK', 'Unalakleet Airport')
INSERT INTO airports2 (112, 'AK', 'DUT', 'Unalaska Airport')
INSERT INTO airports2 (113, 'AK', 'VDZ', 'Valdez Pioneer Field')
INSERT INTO airports2 (114, 'AK', 'AWI', 'Wainwright Airport')
INSERT INTO airports2 (115, 'AK', 'WRG', 'Wrangell Airport')
INSERT INTO airports2 (116, 'AK', 'YAK', 'Yakutat Airport')
INSERT INTO airports2 (117, 'AL', 'ANB', 'Anniston Municipal Airport')
INSERT INTO airports2 (118, 'AL', 'BHM', 'Birmingham International Airport')
INSERT INTO airports2 (119, 'AL', 'DHN', 'Dothan Regional Airport')
INSERT INTO airports2 (120, 'AL', 'HSV', 'Huntsville International Airport')
INSERT INTO airports2 (121, 'AL', 'MOB', 'Mobile Regional Airport')
INSERT INTO airports2 (122, 'AL', 'MGM', 'Montgomery Regional Airport')
INSERT INTO airports2 (123, 'AL', 'MSL', 'Northwest Alabama Regional Airport')
INSERT INTO airports2 (124, 'AL', 'ASN', 'Talladega Municipal Airport')
INSERT INTO airports2 (125, 'AL', 'TCL', 'Tuscaloosa Regional Airport')
INSERT INTO airports2 (126, 'AR', 'FYV', 'Drake Field')
INSERT INTO airports2 (127, 'AR', 'XNA', 'Northwest Arkansas Regional Airport')
INSERT INTO airports2 (128, 'AR', 'FSM', 'Fort Smith Airport')
INSERT INTO airports2 (129, 'AR', 'HRO', 'Boone County Airport')
INSERT INTO airports2 (130, 'AR', 'HOT', 'Memorial Field Airport')
INSERT INTO airports2 (131, 'AR', 'JBR', 'Jonesboro Municipal Airport')
INSERT INTO airports2 (132, 'AR', 'LIT', 'Little Rock National Airport')
INSERT INTO airports2 (133, 'AR', 'BPK', 'Baxter County Regional Airport')
INSERT INTO airports2 (134, 'AR', 'TXK', 'Texarkana Regional Airport')
INSERT INTO airports2 (135, 'AS', 'FAQ', 'Fitiuta Airport')
INSERT INTO airports2 (136, 'AS', 'Z08', 'Ofu Airport')
INSERT INTO airports2 (137, 'AS', 'PPG', 'Pago Pago International Airport')
INSERT INTO airports2 (138, 'AZ', 'IFP', 'Laughlin/Bullhead International Airport')
INSERT INTO airports2 (139, 'AZ', 'FLG', 'Flagstaff Pulliam Airport')
INSERT INTO airports2 (140, 'AZ', 'FHU', 'Sierra Vista Municipal Airport')
INSERT INTO airports2 (141, 'AZ', 'GYR', 'Phoenix Goodyear Airport')
INSERT INTO airports2 (142, 'AZ', 'GCN', 'Grand Canyon National Park Airport')
INSERT INTO airports2 (143, 'AZ', 'IGM', 'Kingman Airport')
INSERT INTO airports2 (144, 'AZ', 'HII', 'Lake Havasu City Airport')
INSERT INTO airports2 (145, 'AZ', 'MZJ', 'Pinal Airpark')
INSERT INTO airports2 (146, 'AZ', 'IWA', 'Williams Gateway Airport')
INSERT INTO airports2 (147, 'AZ', 'PGA', 'Page Municipal Airport')
INSERT INTO airports2 (148, 'AZ', '1G4', 'Grand Canyon West Airport')
INSERT INTO airports2 (149, 'AZ', 'DVT', 'Deer Valley Municipal Airport')
INSERT INTO airports2 (150, 'AZ', 'PHX', 'Phoenix Sky Harbor International Airport')
INSERT INTO airports2 (151, 'AZ', 'PRC', 'Ernest A. Love Field Airport')
INSERT INTO airports2 (152, 'AZ', 'SOW', 'Show Low Regional Airport')
INSERT INTO airports2 (153, 'AZ', 'TUS', 'Tucson International Airport')
INSERT INTO airports2 (154, 'AZ', 'YUM', 'Yuma International Airport')
INSERT INTO airports2 (155, 'CA', 'ACV', 'Arcata Airport')
INSERT INTO airports2 (156, 'CA', 'BFL', 'Meadows Field Airport')
INSERT INTO airports2 (157, 'CA', 'BUR', 'Burbank Bob Hope Airport')
INSERT INTO airports2 (158, 'CA', 'CRQ', 'Mc Clellan-Palomar Airport')
INSERT INTO airports2 (159, 'CA', 'CIC', 'Chico Municipal Airport')
INSERT INTO airports2 (160, 'CA', 'CCR', 'Buchanan Field Airport')
INSERT INTO airports2 (161, 'CA', 'CEC', 'Jack Mc Namara Field Airport')
INSERT INTO airports2 (162, 'CA', 'FAT', 'Fresno Air Terminal')
INSERT INTO airports2 (163, 'CA', 'IPL', 'Imperial County Airport')
INSERT INTO airports2 (164, 'CA', 'IYK', 'Inyokern Airport')
INSERT INTO airports2 (165, 'CA', 'LGB', 'Long Beach Airport')
INSERT INTO airports2 (166, 'CA', 'LAX', 'Los Angeles International Airport')
INSERT INTO airports2 (167, 'CA', 'MMH', 'Mammoth Yosemite Airport')
INSERT INTO airports2 (168, 'CA', 'MCE', 'Merced Municipal Airport')
INSERT INTO airports2 (169, 'CA', 'MOD', 'Modesto City-County Airport')
INSERT INTO airports2 (170, 'CA', 'MRY', 'Monterey Peninsula Airport')
INSERT INTO airports2 (171, 'CA', 'OAK', 'Oakland International Airport')
INSERT INTO airports2 (172, 'CA', 'ONT', 'Ontario International Airport')
INSERT INTO airports2 (173, 'CA', 'SNA', 'John Wayne Airport')
INSERT INTO airports2 (174, 'CA', 'OXR', 'Oxnard Airport')
INSERT INTO airports2 (175, 'CA', 'PSP', 'Palm Springs International Airport')
INSERT INTO airports2 (176, 'CA', 'PMD', 'Palmdale Regional Airport')
INSERT INTO airports2 (177, 'CA', 'PRB', 'Paso Robles Municipal Airport')
INSERT INTO airports2 (178, 'CA', 'RDD', 'Redding Municipal Airport')
INSERT INTO airports2 (179, 'CA', 'SMF', 'Sacramento International Airport')
INSERT INTO airports2 (180, 'CA', 'MCC', 'Mc Clellan Airfield')
INSERT INTO airports2 (181, 'CA', 'SBD', 'San Bernardino International Airport')
INSERT INTO airports2 (182, 'CA', 'SAN', 'San Diego International Airport')
INSERT INTO airports2 (183, 'CA', 'SFO', 'San Francisco International Airport')
INSERT INTO airports2 (184, 'CA', 'SJC', 'San Jose International Airport')
INSERT INTO airports2 (185, 'CA', 'SBP', 'San Luis County Regional Airport')
INSERT INTO airports2 (186, 'CA', 'SBA', 'Santa Barbara Airport')
INSERT INTO airports2 (187, 'CA', 'SMX', 'Santa Maria Public Airport')
INSERT INTO airports2 (188, 'CA', 'STS', 'Sonoma County Airport')
INSERT INTO airports2 (189, 'CA', 'TVL', 'Lake Tahoe Airport')
INSERT INTO airports2 (190, 'CA', 'SCK', 'Stockton Metropolitan Airport')
INSERT INTO airports2 (191, 'CA', 'VCV', 'Southern California Logistics Airport')
INSERT INTO airports2 (192, 'CA', 'VIS', 'Visalia Municipal Airport')
INSERT INTO airports2 (193, 'CO', 'ALS', 'San Luis Valley Regional Airport')
INSERT INTO airports2 (194, 'CO', 'ASE', 'Aspen-Pitkin County Airport')
INSERT INTO airports2 (195, 'CO', 'COS', 'Colorado Springs Airport')
INSERT INTO airports2 (196, 'CO', 'CEZ', 'Cortez Municipal Airport')
INSERT INTO airports2 (197, 'CO', 'DEN', 'Denver International Airport')
INSERT INTO airports2 (198, 'CO', 'DRO', 'Durango-La Plata County Airport')
INSERT INTO airports2 (199, 'CO', 'EGE', 'Eagle County Regional Airport')
INSERT INTO airports2 (200, 'CO', 'FNL', 'Fort Collins-Loveland Municipal Airport')
INSERT INTO airports2 (201, 'CO', 'GJT', 'Walker Field Airport')
INSERT INTO airports2 (202, 'CO', 'GUC', 'Gunnison-Crested Butte Regional Airport')
INSERT INTO airports2 (203, 'CO', 'HDN', 'Yampa Valley Regional Airport')
INSERT INTO airports2 (204, 'CO', 'LAA', 'Lamar Municipal Airport')
INSERT INTO airports2 (205, 'CO', 'MTJ', 'Montrose Regional Airport')
INSERT INTO airports2 (206, 'CO', 'PUB', 'Pueblo Memorial Airport')
INSERT INTO airports2 (207, 'CO', 'TEX', 'Telluride Regional Airport')
INSERT INTO airports2 (208, 'CQ', 'GRO', 'Rota International Airport')
INSERT INTO airports2 (209, 'CQ', 'GSN', 'Saipan International Airport')
INSERT INTO airports2 (210, 'CQ', 'TNI', 'Tinian International Airport')
INSERT INTO airports2 (211, 'CT', 'BDR', 'Igor I Sikorsky Memorial Airport')
INSERT INTO airports2 (212, 'CT', 'DXR', 'Danbury Municipal Airport')
INSERT INTO airports2 (213, 'CT', 'GON', 'Groton-New London Airport')
INSERT INTO airports2 (214, 'CT', 'HFD', 'Hartford-Brainard Airport')
INSERT INTO airports2 (215, 'CT', 'HVN', 'Tweed New Haven Regional Airport')
INSERT INTO airports2 (216, 'CT', 'OXC', 'Waterbury-Oxford Airport')
INSERT INTO airports2 (217, 'CT', 'BDL', 'Bradley International Airport')
INSERT INTO airports2 (218, 'DC', 'IAD', 'Washington Dulles International Airport')
INSERT INTO airports2 (219, 'DC', 'DCA', 'Ronald Reagan Washington National Airport')
INSERT INTO airports2 (220, 'DE', 'GED', 'Sussex County Airport')
INSERT INTO airports2 (221, 'DE', 'ILG', 'New Castle Airport')
INSERT INTO airports2 (222, 'FL', 'DAB', 'Daytona Beach International Airport')
INSERT INTO airports2 (223, 'FL', 'FLL', 'Fort Lauderdale Hollywood International Airport')
INSERT INTO airports2 (224, 'FL', 'RSW', 'Southwest Florida International Airport')
INSERT INTO airports2 (225, 'FL', 'GNV', 'Gainesville Regional Airport')
INSERT INTO airports2 (226, 'FL', 'JAX', 'Jacksonville International Airport')
INSERT INTO airports2 (227, 'FL', 'VQQ', 'Cecil Field Airport')
INSERT INTO airports2 (228, 'FL', 'EYW', 'Key West International Airport')
INSERT INTO airports2 (229, 'FL', 'LAL', 'Lakeland Linder Regional Airport')
INSERT INTO airports2 (230, 'FL', 'MTH', 'Florida Keys Marathon Airport')
INSERT INTO airports2 (231, 'FL', 'MLB', 'Melbourne International Airport')
INSERT INTO airports2 (232, 'FL', 'MIA', 'Miami International Airport')
INSERT INTO airports2 (233, 'FL', 'X44', 'Miami Airport')
INSERT INTO airports2 (234, 'FL', 'APF', 'Naples Municipal Airport')
INSERT INTO airports2 (235, 'FL', 'OCF', 'Ocala International Airport')
INSERT INTO airports2 (236, 'FL', 'MCO', 'Orlando International Airport')
INSERT INTO airports2 (237, 'FL', 'PFN', 'Panama City-Bay County International Airport')
INSERT INTO airports2 (238, 'FL', 'PNS', 'Pensacola Regional Airport')
INSERT INTO airports2 (239, 'FL', 'PGD', 'Charlotte County Airport')
INSERT INTO airports2 (240, 'FL', 'PIE', 'St. Petersburg-Clearwater International Airport')
INSERT INTO airports2 (241, 'FL', 'SFB', 'Orlando Sanford International Airport')
INSERT INTO airports2 (242, 'FL', 'SRQ', 'Sarasota-Bradenton International Airport')
INSERT INTO airports2 (243, 'FL', 'SGJ', 'St Augustine Airport')
INSERT INTO airports2 (244, 'FL', 'TLH', 'Tallahassee Regional Airport')
INSERT INTO airports2 (245, 'FL', 'TPA', 'Tampa International Airport')
INSERT INTO airports2 (246, 'FL', 'TIX', 'Space Coast Regional Airport')
INSERT INTO airports2 (247, 'FL', 'VPS', 'Fort Walton Beach Airport')
INSERT INTO airports2 (248, 'FL', 'VRB', 'Vero Beach Municipal Airport')
INSERT INTO airports2 (249, 'FL', 'PBI', 'Palm Beach International Airport')
INSERT INTO airports2 (250, 'GA', 'ABY', 'Southwest Georgia Regional Airport')
INSERT INTO airports2 (251, 'GA', 'AHN', 'Athens/Ben Epps Airport')
INSERT INTO airports2 (252, 'GA', 'ATL', 'Atlanta International Airport')
INSERT INTO airports2 (253, 'GA', 'AGS', 'Augusta Regional Airport')
INSERT INTO airports2 (254, 'GA', 'BQK', 'Brunswick Golden Isles Airport')
INSERT INTO airports2 (255, 'GA', 'CSG', 'Columbus Metropolitan Airport')
INSERT INTO airports2 (256, 'GA', 'MCN', 'Middle Georgia Regional Airport')
INSERT INTO airports2 (257, 'GA', 'RMG', 'Richard B Russell Airport')
INSERT INTO airports2 (258, 'GA', 'SAV', 'Savannah/Hilton Head International Airport')
INSERT INTO airports2 (259, 'GA', 'VLD', 'Valdosta Regional Airport')
INSERT INTO airports2 (260, 'GU', 'GUM', 'Guam International Airport')
INSERT INTO airports2 (261, 'HI', 'HNM', 'Hana Airport')
INSERT INTO airports2 (262, 'HI', 'ITO', 'Hilo International Airport')
INSERT INTO airports2 (263, 'HI', 'HNL', 'Honolulu International Airport')
INSERT INTO airports2 (264, 'HI', 'OGG', 'Kahului Airport')
INSERT INTO airports2 (265, 'HI', 'MUE', 'Waimea - Kohala Airport')
INSERT INTO airports2 (266, 'HI', 'MKK', 'Molokai Airport')
INSERT INTO airports2 (267, 'HI', 'KOA', 'Kona International Airport')
INSERT INTO airports2 (268, 'HI', 'LNY', 'Lanai Airport')
INSERT INTO airports2 (269, 'HI', 'LIH', 'Lihue Airport')
INSERT INTO airports2 (270, 'IA', 'BRL', 'Southeast Iowa Regional Airport')
INSERT INTO airports2 (271, 'IA', 'CID', 'Cedar Rapids Eastern Iowa Airport')
INSERT INTO airports2 (272, 'IA', 'CWI', 'Clinton Municipal Airport')
INSERT INTO airports2 (273, 'IA', 'DSM', 'Des Moines International Airport')
INSERT INTO airports2 (274, 'IA', 'DBQ', 'Dubuque Regional Airport')
INSERT INTO airports2 (275, 'IA', 'FOD', 'Fort Dodge Regional Airport')
INSERT INTO airports2 (276, 'IA', 'MCW', 'Mason City Municipal Airport')
INSERT INTO airports2 (277, 'IA', 'OTM', 'Ottumwa Industrial Airport')
INSERT INTO airports2 (278, 'IA', 'SUX', 'Sioux Gateway Airport')
INSERT INTO airports2 (279, 'IA', 'ALO', 'Waterloo Regional Airport')
INSERT INTO airports2 (280, 'ID', 'BOI', 'Boise Airport')
INSERT INTO airports2 (281, 'ID', 'COE', 'Coeur Dalene Airport')
INSERT INTO airports2 (282, 'ID', 'SUN', 'Friedman Memorial Airport')
INSERT INTO airports2 (283, 'ID', 'IDA', 'Idaho Falls Regional Airport')
INSERT INTO airports2 (284, 'ID', 'LWS', 'Lewiston-Nez Perce County Airport')
INSERT INTO airports2 (285, 'ID', 'PIH', 'Pocatello Regional Airport')
INSERT INTO airports2 (286, 'ID', 'TWF', 'Magic Valley Regional Airport')
INSERT INTO airports2 (287, 'IL', 'ALN', 'St Louis Regional Airport')
INSERT INTO airports2 (288, 'IL', 'BLV', 'Midamerica Airport')
INSERT INTO airports2 (289, 'IL', 'BMI', 'Central Illinois Regional Airport')
INSERT INTO airports2 (290, 'IL', 'MDH', 'Southern Illinois Airport')
INSERT INTO airports2 (291, 'IL', 'CMI', 'Champaign Willard Airport')
INSERT INTO airports2 (292, 'IL', 'MDW', 'Chicago Midway Airport')
INSERT INTO airports2 (293, 'IL', 'ORD', 'Chicago Ohare International Airport')
INSERT INTO airports2 (294, 'IL', 'CGX', 'Merrill C Meigs Field')
INSERT INTO airports2 (295, 'IL', 'DNV', 'Vermilion County Airport')
INSERT INTO airports2 (296, 'IL', 'DEC', 'Decatur Airport')
INSERT INTO airports2 (297, 'IL', 'MWA', 'Williamson County Regional Airport')
INSERT INTO airports2 (298, 'IL', 'MTO', 'Coles County Memorial Airport')
INSERT INTO airports2 (299, 'IL', 'MLI', 'Quad City International Airport')
INSERT INTO airports2 (300, 'IL', 'MVN', 'Mount Vernon Airport')
INSERT INTO airports2 (301, 'IL', 'PIA', 'Peoria Regional Airport')
INSERT INTO airports2 (302, 'IL', 'UIN', 'Quincy Regional Airport - Baldwin Field')
INSERT INTO airports2 (303, 'IL', 'RFD', 'Greater Rockford Airport')
INSERT INTO airports2 (304, 'IL', 'SPI', 'Abraham Lincoln Capital Airport')
INSERT INTO airports2 (305, 'IL', 'SQI', 'Whiteside County Airport')
INSERT INTO airports2 (306, 'IN', 'AID', 'Anderson Municipal Airport')
INSERT INTO airports2 (307, 'IN', 'BMG', 'Monroe County Airport')
INSERT INTO airports2 (308, 'IN', 'BAK', 'Columbus Municipal Airport')
INSERT INTO airports2 (309, 'IN', 'EKM', 'Elkhart Municipal Airport')
INSERT INTO airports2 (310, 'IN', 'EVV', 'Evansville Regional Airport')
INSERT INTO airports2 (311, 'IN', 'FWA', 'Fort Wayne International Airport')
INSERT INTO airports2 (312, 'IN', 'GYY', 'Gary Regional Airport')
INSERT INTO airports2 (313, 'IN', 'IND', 'Indianapolis International Airport')
INSERT INTO airports2 (314, 'IN', 'MQJ', 'Mount Comfort Airport')
INSERT INTO airports2 (315, 'IN', 'LAF', 'Purdue University Airport')
INSERT INTO airports2 (316, 'IN', 'MIE', 'Delaware County Airport')
INSERT INTO airports2 (317, 'IN', 'SBN', 'South Bend Regional Airport')
INSERT INTO airports2 (318, 'IN', 'HUF', 'Terre Haute International Airport')
INSERT INTO airports2 (319, 'IN', 'VPZ', 'Porter County Municipal Airport')
INSERT INTO airports2 (320, 'KS', 'DDC', 'Dodge City Regional Airport')
INSERT INTO airports2 (321, 'KS', 'GCK', 'Garden City Regional Airport')
INSERT INTO airports2 (322, 'KS', 'GLD', 'Goodland Municipal Airport')
INSERT INTO airports2 (323, 'KS', 'GBD', 'Great Bend Municipal Airport')
INSERT INTO airports2 (324, 'KS', 'HYS', 'Hays Regional Airport')
INSERT INTO airports2 (325, 'KS', 'HUT', 'Hutchinson Municipal Airport')
INSERT INTO airports2 (326, 'KS', 'LBL', 'Liberal Municipal Airport')
INSERT INTO airports2 (327, 'KS', 'MHK', 'Manhattan Regional Airport')
INSERT INTO airports2 (328, 'KS', 'IXD', 'Olathe/New Century Aircenter Airport')
INSERT INTO airports2 (329, 'KS', 'SLN', 'Salina Municipal Airport')
INSERT INTO airports2 (330, 'KS', 'FOE', 'Forbes Field Airport')
INSERT INTO airports2 (331, 'KS', 'ICT', 'Wichita Mid-Continent Airport')
INSERT INTO airports2 (332, 'KY', 'BWG', 'Bowling Green-Warren County Regional Airport')
INSERT INTO airports2 (333, 'KY', 'LEX', 'Blue Grass Airport')
INSERT INTO airports2 (334, 'KY', 'SDF', 'Louisville International Airport')
INSERT INTO airports2 (335, 'KY', 'OWB', 'Owensboro-Daviess County Airport')
INSERT INTO airports2 (336, 'KY', 'PAH', 'Paducah Barkley Regional Airport')
INSERT INTO airports2 (337, 'LA', 'AEX', 'Alexandria International Airport')
INSERT INTO airports2 (338, 'LA', 'ESF', 'Esler Regional Airport')
INSERT INTO airports2 (339, 'LA', 'BTR', 'Baton Rouge International Airport')
INSERT INTO airports2 (340, 'LA', 'LCH', 'Lake Charles Regional Airport')
INSERT INTO airports2 (341, 'LA', 'LFT', 'Lafayette Regional Airport')
INSERT INTO airports2 (342, 'LA', 'MLU', 'Monroe Regional Airport')
INSERT INTO airports2 (343, 'LA', 'MSY', 'New Orleans International Airport')
INSERT INTO airports2 (344, 'LA', 'NEW', 'Lakefront Airport')
INSERT INTO airports2 (345, 'LA', 'SHV', 'Shreveport Regional Airport')
INSERT INTO airports2 (346, 'LA', 'TVR', 'Vicksburg Tallulah Regional Airport')
INSERT INTO airports2 (347, 'MA', 'BED', 'Bedford Hanscom Field')
INSERT INTO airports2 (348, 'MA', 'BOS', 'Boston Logan International Airport')
INSERT INTO airports2 (349, 'MA', 'HYA', 'Barnstable Municipal Airport')
INSERT INTO airports2 (350, 'MA', 'ACK', 'Nantucket Memorial Airport')
INSERT INTO airports2 (351, 'MA', 'EWB', 'New Bedford Regional Airport')
INSERT INTO airports2 (352, 'MA', 'PVC', 'Provincetown Municipal Airport')
INSERT INTO airports2 (353, 'MA', 'CEF', 'Westover Metropolitan Airport')
INSERT INTO airports2 (354, 'MA', 'MVY', 'Marthas Vineyard Airport')
INSERT INTO airports2 (355, 'MA', 'BAF', 'Barnes Municipal Airport')
INSERT INTO airports2 (356, 'MA', 'ORH', 'Worcester Regional Airport')
INSERT INTO airports2 (357, 'MD', 'BWI', 'Baltimore / Washington International Airport')
INSERT INTO airports2 (358, 'MD', 'HGR', 'Hagerstown Regional Airport')
INSERT INTO airports2 (359, 'MD', 'SBY', 'Salisbury-Ocean City Wicomico Regional Airport')
INSERT INTO airports2 (360, 'ME', 'AUG', 'Augusta State Airport')
INSERT INTO airports2 (361, 'ME', 'BGR', 'Bangor International Airport')
INSERT INTO airports2 (362, 'ME', 'BHB', 'Hancock County-Bar Harbor Airport')
INSERT INTO airports2 (363, 'ME', 'PWM', 'Portland International Jetport')
INSERT INTO airports2 (364, 'ME', 'PQI', 'Northern Maine Regional Airport')
INSERT INTO airports2 (365, 'ME', 'RKD', 'Knox County Regional Airport')
INSERT INTO airports2 (366, 'MI', 'APN', 'Alpena County Regional Airport')
INSERT INTO airports2 (367, 'MI', 'BTL', 'W K Kellogg Airport')
INSERT INTO airports2 (368, 'MI', 'ACB', 'Bellaire/Antrim County Airport')
INSERT INTO airports2 (369, 'MI', 'BEH', 'Southwest Michigan Regional Airport')
INSERT INTO airports2 (370, 'MI', 'CVX', 'Charlevoix Municipal Airport')
INSERT INTO airports2 (371, 'MI', 'DTW', 'Detroit Metro Airport')
INSERT INTO airports2 (372, 'MI', 'DET', 'Detroit City Airport')
INSERT INTO airports2 (373, 'MI', 'ESC', 'Delta County Airport')
INSERT INTO airports2 (374, 'MI', 'FNT', 'Bishop International Airport')
INSERT INTO airports2 (375, 'MI', 'GLR', 'Gaylord Regional Airport')
INSERT INTO airports2 (376, 'MI', 'GRR', 'Gerald R. Ford International Airport')
INSERT INTO airports2 (377, 'MI', 'CMX', 'Houghton County Memorial Airport')
INSERT INTO airports2 (378, 'MI', 'IMT', 'Iron Mountain Airport')
INSERT INTO airports2 (379, 'MI', 'IWD', 'Gogebic-Iron County Airport')
INSERT INTO airports2 (380, 'MI', 'JXN', 'Jackson County Airport')
INSERT INTO airports2 (381, 'MI', 'AZO', 'Kalamazoo/Battle Creek International Airport')
INSERT INTO airports2 (382, 'MI', 'LAN', 'Lansing Capital City Airport')
INSERT INTO airports2 (383, 'MI', 'MBL', 'Manistee County-Blacker')
INSERT INTO airports2 (384, 'MI', 'SAW', 'Sawyer International Airport')
INSERT INTO airports2 (385, 'MI', 'MNM', 'Menominee-Marinette Twin County Airport')
INSERT INTO airports2 (386, 'MI', 'MKG', 'Muskegon County Airport')
INSERT INTO airports2 (387, 'MI', 'PLN', 'Pellston Regional Airport')
INSERT INTO airports2 (388, 'MI', 'PTK', 'Oakland County International Airport')
INSERT INTO airports2 (389, 'MI', 'MBS', 'Saginaw International Airport')
INSERT INTO airports2 (390, 'MI', 'CIU', 'Chippewa County International Airport')
INSERT INTO airports2 (391, 'MI', 'TVC', 'Cherry Capital Airport')
INSERT INTO airports2 (392, 'MN', 'AXN', 'Chandler Field Airport')
INSERT INTO airports2 (393, 'MN', 'BDE', 'Baudette International Airport')
INSERT INTO airports2 (394, 'MN', 'BJI', 'Bemidji Regional Airport')
INSERT INTO airports2 (395, 'MN', 'BRD', 'Brainerd Lakes Regional Airport')
INSERT INTO airports2 (396, 'MN', 'DLH', 'Duluth International Airport')
INSERT INTO airports2 (397, 'MN', 'ELO', 'Ely Municipal Airport')
INSERT INTO airports2 (398, 'MN', 'FRM', 'Fairmont Municipal Airport')
INSERT INTO airports2 (399, 'MN', 'GPZ', 'Grand Rapids/Itasca County Airport')
INSERT INTO airports2 (400, 'MN', 'HIB', 'Chisholm-Hibbing Airport')
INSERT INTO airports2 (401, 'MN', 'INL', 'Falls International Airport')
INSERT INTO airports2 (402, 'MN', 'MKT', 'Mankato Regional Airport')
INSERT INTO airports2 (403, 'MN', 'MSP', 'Minneapolis/St. Paul International Airport')
INSERT INTO airports2 (404, 'MN', 'RST', 'Rochester International Airport')
INSERT INTO airports2 (405, 'MN', 'STC', 'St Cloud Regional Airport')
INSERT INTO airports2 (406, 'MN', 'STP', 'St Paul Downtown Airport / Holman Field')
INSERT INTO airports2 (407, 'MN', 'TVF', 'Thief River Falls Regional Airport')
INSERT INTO airports2 (408, 'MN', 'ILL', 'Willmar Municipal Airport')
INSERT INTO airports2 (409, 'MN', 'OTG', 'Worthington Municipal Airport')
INSERT INTO airports2 (410, 'MO', 'CGI', 'Cape Girardeau Regional Airport')
INSERT INTO airports2 (411, 'MO', 'COU', 'Columbia Regional Airport')
INSERT INTO airports2 (412, 'MO', 'TBN', 'Waynesville Regional Airport At Forney Field')
INSERT INTO airports2 (413, 'MO', 'JEF', 'Jefferson City Memorial Airport')
INSERT INTO airports2 (414, 'MO', 'JLN', 'Joplin Regional Airport')
INSERT INTO airports2 (415, 'MO', 'AIZ', 'Lee C Fine Memorial Airport')
INSERT INTO airports2 (416, 'MO', 'MCI', 'Kansas City International Airport')
INSERT INTO airports2 (417, 'MO', 'MKC', 'Charles B. Wheeler Downtown Airport')
INSERT INTO airports2 (418, 'MO', 'IRK', 'Kirksville Regional Airport')
INSERT INTO airports2 (419, 'MO', 'PLK', 'M Graham Clark - Taney County Airport')
INSERT INTO airports2 (420, 'MO', 'STL', 'Lambert-St. Louis International Airport')
INSERT INTO airports2 (421, 'MO', 'SGF', 'Springfield Branson Regional Airport')
INSERT INTO airports2 (422, 'MO', 'STJ', 'Rosecrans Memorial Airport')
INSERT INTO airports2 (423, 'MO', 'SUS', 'Spirit Of St Louis Airport')
INSERT INTO airports2 (424, 'MQ', 'MDY', 'Henderson Field Airport')
INSERT INTO airports2 (425, 'MS', 'GTR', 'Golden Triangle Regional Airport')
INSERT INTO airports2 (426, 'MS', 'GLH', 'Mid Delta Regional Airport')
INSERT INTO airports2 (427, 'MS', 'GPT', 'Gulfport-Biloxi International Airport')
INSERT INTO airports2 (428, 'MS', 'PIB', 'Hattiesburg-Laurel Regional Airport')
INSERT INTO airports2 (429, 'MS', 'JAN', 'Jackson-Evers International Airport')
INSERT INTO airports2 (430, 'MS', 'HKS', 'Hawkins Field Airport')
INSERT INTO airports2 (431, 'MS', 'MEI', 'Key Field Airport')
INSERT INTO airports2 (432, 'MS', 'UOX', 'University-Oxford Airport')
INSERT INTO airports2 (433, 'MS', 'PQL', 'Trent Lott International Airport')
INSERT INTO airports2 (434, 'MS', 'TUP', 'Tupelo Regional Airport')
INSERT INTO airports2 (435, 'MT', 'BIL', 'Billings Logan International Airport')
INSERT INTO airports2 (436, 'MT', 'BZN', 'Bozeman Gallatin Field Airport')
INSERT INTO airports2 (437, 'MT', 'BTM', 'Bert Mooney Airport')
INSERT INTO airports2 (438, 'MT', 'GGW', 'Wokal Field/Glasgow International Airport')
INSERT INTO airports2 (439, 'MT', 'GTF', 'Great Falls International Airport')
INSERT INTO airports2 (440, 'MT', 'HLN', 'Helena Regional Airport')
INSERT INTO airports2 (441, 'MT', 'GPI', 'Glacier Park International Airport')
INSERT INTO airports2 (442, 'MT', 'MSO', 'Missoula International Airport')
INSERT INTO airports2 (443, 'MT', 'SDY', 'Sidney-Richland Municipal Airport')
INSERT INTO airports2 (444, 'MT', 'WYS', 'West Yellowstone Airport')
INSERT INTO airports2 (445, 'NC', 'AVL', 'Asheville Regional Airport')
INSERT INTO airports2 (446, 'NC', 'CLT', 'Charlotte/Douglas International Airport')
INSERT INTO airports2 (447, 'NC', 'FAY', 'Fayetteville Regional/Grannis Field Airport')
INSERT INTO airports2 (448, 'NC', 'GSO', 'Piedmont Triad International Airport')
INSERT INTO airports2 (449, 'NC', 'PGV', 'Pitt-Greenville Airport')
INSERT INTO airports2 (450, 'NC', 'HKY', 'Hickory Regional Airport')
INSERT INTO airports2 (451, 'NC', 'OAJ', 'Jacksonville/Albert J Ellis Airport')
INSERT INTO airports2 (452, 'NC', 'ISO', 'Kinston Regional Jetport')
INSERT INTO airports2 (453, 'NC', 'MQI', 'Dare County Regional Airport')
INSERT INTO airports2 (454, 'NC', 'EWN', 'Craven County Regional Airport')
INSERT INTO airports2 (455, 'NC', 'SOP', 'Moore County Airport')
INSERT INTO airports2 (456, 'NC', 'RDU', 'Raleigh-Durham International Airport')
INSERT INTO airports2 (457, 'NC', 'RWI', 'Rocky Mount-Wilson Regional Airport')
INSERT INTO airports2 (458, 'NC', 'ILM', 'Wilmington International Airport')
INSERT INTO airports2 (459, 'NC', 'INT', 'Smith Reynolds Airport')
INSERT INTO airports2 (460, 'ND', 'BIS', 'Bismarck Municipal Airport')
INSERT INTO airports2 (461, 'ND', 'DVL', 'Devils Lake Municipal Airport')
INSERT INTO airports2 (462, 'ND', 'DIK', 'Dickinson - Theodore Roosevelt Regional Airport')
INSERT INTO airports2 (463, 'ND', 'FAR', 'Hector International Airport')
INSERT INTO airports2 (464, 'ND', 'GFK', 'Grand Forks International Airport')
INSERT INTO airports2 (465, 'ND', 'JMS', 'Jamestown Regional Airport')
INSERT INTO airports2 (466, 'ND', 'MOT', 'Minot International Airport')
INSERT INTO airports2 (467, 'ND', 'ISN', 'Sloulin Field International Airport')
INSERT INTO airports2 (468, 'NE', 'AIA', 'Alliance Municipal Airport')
INSERT INTO airports2 (469, 'NE', 'GRI', 'Central Nebraska Regional Airport')
INSERT INTO airports2 (470, 'NE', 'EAR', 'Kearney Municipal Airport')
INSERT INTO airports2 (471, 'NE', 'LNK', 'Lincoln Airport')
INSERT INTO airports2 (472, 'NE', 'MCK', 'Mc Cook Regional Airport')
INSERT INTO airports2 (473, 'NE', 'OFK', 'Karl Stefan Memorial Airport')
INSERT INTO airports2 (474, 'NE', 'LBF', 'North Platte Regional Airport Lee Bird Field')
INSERT INTO airports2 (475, 'NE', 'OMA', 'Eppley Airfield')
INSERT INTO airports2 (476, 'NE', 'BFF', 'Western Nebraska Regional Airport')
INSERT INTO airports2 (477, 'NH', 'EEN', 'Keene/Dillant-Hopkins Airport')
INSERT INTO airports2 (478, 'NH', 'LEB', 'Lebanon Municipal Airport')
INSERT INTO airports2 (479, 'NH', 'MHT', 'Manchester Airport')
INSERT INTO airports2 (480, 'NH', 'PSM', 'Pease International Airport')
INSERT INTO airports2 (481, 'NJ', 'AIY', 'Atlantic City Municipal Airport/Bader Field')
INSERT INTO airports2 (482, 'NJ', 'BLM', 'Monmouth Executive Airport')
INSERT INTO airports2 (483, 'NJ', 'CDW', 'Essex County Airport')
INSERT INTO airports2 (484, 'NJ', 'ACY', 'Atlantic City International Airport')
INSERT INTO airports2 (485, 'NJ', 'MIV', 'Millville Municipal Airport')
INSERT INTO airports2 (486, 'NJ', 'MMU', 'Morristown Municipal Airport')
INSERT INTO airports2 (487, 'NJ', 'EWR', 'Newark Liberty International Airport')
INSERT INTO airports2 (488, 'NJ', 'TEB', 'Teterboro Airport')
INSERT INTO airports2 (489, 'NJ', 'MJX', 'Robert J. Miller Air Park')
INSERT INTO airports2 (490, 'NJ', 'TTN', 'Trenton Mercer Airport')
INSERT INTO airports2 (491, 'NJ', 'WWD', 'Cape May County Airport')
INSERT INTO airports2 (492, 'NM', 'ALM', 'Alamogordo-White Sands Regional Airport')
INSERT INTO airports2 (493, 'NM', 'ABQ', 'Albuquerque International Sunport')
INSERT INTO airports2 (494, 'NM', 'CNM', 'Cavern City Air Terminal')
INSERT INTO airports2 (495, 'NM', 'FMN', 'Four Corners Regional Airport')
INSERT INTO airports2 (496, 'NM', 'GUP', 'Gallup Municipal Airport')
INSERT INTO airports2 (497, 'NM', 'HOB', 'Lea County Regional Airport')
INSERT INTO airports2 (498, 'NM', 'LRU', 'Las Cruces International Airport')
INSERT INTO airports2 (499, 'NM', 'ROW', 'Roswell Industrial Air Center Airport')
INSERT INTO airports2 (500, 'NM', 'SRR', 'Sierra Blanca Regional Airport')
INSERT INTO airports2 (501, 'NM', 'SAF', 'Santa Fe Municipal Airport')
INSERT INTO airports2 (502, 'NM', 'SVC', 'Grant County Airport')
INSERT INTO airports2 (503, 'NM', 'SKX', 'Taos Regional Airport')
INSERT INTO airports2 (504, 'NV', 'EKO', 'Elko Regional Airport')
INSERT INTO airports2 (505, 'NV', 'ELY', 'Ely Airport')
INSERT INTO airports2 (506, 'NV', 'LAS', 'Mccarran International Airport')
INSERT INTO airports2 (507, 'NV', 'VGT', 'North Las Vegas Air Terminal')
INSERT INTO airports2 (508, 'NV', 'HND', 'Henderson Executive Airport')
INSERT INTO airports2 (509, 'NV', 'RNO', 'Reno-Tahoe International Airport')
INSERT INTO airports2 (510, 'NY', 'ALB', 'Albany International Airport')
INSERT INTO airports2 (511, 'NY', 'BGM', 'Greater Binghamton Airport')
INSERT INTO airports2 (512, 'NY', 'BUF', 'Buffalo Niagara International Airport')
INSERT INTO airports2 (513, 'NY', 'ELM', 'Elmira / Corning Regional Airport')
INSERT INTO airports2 (514, 'NY', 'FRG', 'Republic Airport')
INSERT INTO airports2 (515, 'NY', 'GFL', 'Floyd Bennett Memorial Airport')
INSERT INTO airports2 (516, 'NY', 'ISP', 'Macarthur Airport')
INSERT INTO airports2 (517, 'NY', 'ITH', 'Ithaca Tompkins Regional Airport')
INSERT INTO airports2 (518, 'NY', 'JHW', 'Chautauqua County/Jamestown Airport')
INSERT INTO airports2 (519, 'NY', 'MSS', 'Massena International Airport')
INSERT INTO airports2 (520, 'NY', 'MSV', 'Sullivan County International Airport')
INSERT INTO airports2 (521, 'NY', 'JFK', 'John F. Kennedy International Airport')
INSERT INTO airports2 (522, 'NY', 'LGA', 'La Guardia Airport')
INSERT INTO airports2 (523, 'NY', 'JRB', 'Downtown Manhattan Heliport')
INSERT INTO airports2 (524, 'NY', 'SWF', 'Stewart International Airport')
INSERT INTO airports2 (525, 'NY', 'OGS', 'Ogdensburg International Airport')
INSERT INTO airports2 (526, 'NY', 'PLB', 'Clinton County Airport')
INSERT INTO airports2 (527, 'NY', 'POU', 'Dutchess County Airport')
INSERT INTO airports2 (528, 'NY', 'ROC', 'Greater Rochester International Airport')
INSERT INTO airports2 (529, 'NY', 'RME', 'Griffiss Airpark')
INSERT INTO airports2 (530, 'NY', 'SLK', 'Adirondack Regional Airport')
INSERT INTO airports2 (531, 'NY', 'SYR', 'Syracuse Hancock International Airport')
INSERT INTO airports2 (532, 'NY', 'UCA', 'Oneida County Airport')
INSERT INTO airports2 (533, 'NY', 'ART', 'Watertown International Airport')
INSERT INTO airports2 (534, 'NY', 'HPN', 'Westchester County Airport')
INSERT INTO airports2 (535, 'OH', 'CVG', 'Cincinnati / Northern Kentucky International Airport')
INSERT INTO airports2 (536, 'OH', 'LUK', 'Cincinnati Municipal Airport Lunken Field')
INSERT INTO airports2 (537, 'OH', 'CLE', 'Cleveland Hopkins International Airport')
INSERT INTO airports2 (538, 'OH', 'BKL', 'Burke Lakefront Airport')
INSERT INTO airports2 (539, 'OH', 'CGF', 'Cuyahoga County Airport')
INSERT INTO airports2 (540, 'OH', 'CMH', 'Port Columbus International Airport')
INSERT INTO airports2 (541, 'OH', 'LCK', 'Rickenbacker International Airport')
INSERT INTO airports2 (542, 'OH', 'OSU', 'Ohio State University Airport')
INSERT INTO airports2 (543, 'OH', 'DAY', 'Dayton International Airport')
INSERT INTO airports2 (544, 'OH', 'LPR', 'Lorain County Regional Airport')
INSERT INTO airports2 (545, 'OH', 'MFD', 'Mansfield Lahm Regional Airport')
INSERT INTO airports2 (546, 'OH', '3T7', 'Middle Bass Island Airport')
INSERT INTO airports2 (547, 'OH', 'CAK', 'Akron-Canton Airport')
INSERT INTO airports2 (548, 'OH', 'PCW', 'Carl R Keller Field')
INSERT INTO airports2 (549, 'OH', '3W2', 'Put - in - Bay Airport')
INSERT INTO airports2 (550, 'OH', 'SGH', 'Springfield-Beckley Municipal Airport')
INSERT INTO airports2 (551, 'OH', 'TOL', 'Toledo Express Airport')
INSERT INTO airports2 (552, 'OH', 'YNG', 'Youngstown Regional Airport')
INSERT INTO airports2 (553, 'OK', 'WDG', 'Woodring Municipal Airport')
INSERT INTO airports2 (554, 'OK', 'LAW', 'Lawton-Fort Sill Regional Airport')
INSERT INTO airports2 (555, 'OK', 'OKC', 'Will Rogers World Airport')
INSERT INTO airports2 (556, 'OK', 'PNC', 'Ponca City Regional Airport')
INSERT INTO airports2 (557, 'OK', 'SWO', 'Stillwater Regional Airport')
INSERT INTO airports2 (558, 'OK', 'TUL', 'Tulsa International Airport')
INSERT INTO airports2 (559, 'OR', 'AST', 'Astoria Regional Airport')
INSERT INTO airports2 (560, 'OR', 'CVO', 'Corvallis Municipal Airport')
INSERT INTO airports2 (561, 'OR', 'EUG', 'Eugene Airport')
INSERT INTO airports2 (562, 'OR', 'LMT', 'Klamath Falls Airport')
INSERT INTO airports2 (563, 'OR', 'MMV', 'Mc Minnville Municipal Airport')
INSERT INTO airports2 (564, 'OR', 'MFR', 'Medford Rogue Valley International Airport')
INSERT INTO airports2 (565, 'OR', 'ONP', 'Newport Municipal Airport')
INSERT INTO airports2 (566, 'OR', 'OTH', 'North Bend Municipal Airport')
INSERT INTO airports2 (567, 'OR', 'PDT', 'Eastern Oregon Regional Airport At Pendleton')
INSERT INTO airports2 (568, 'OR', 'PDX', 'Portland International Airport')
INSERT INTO airports2 (569, 'OR', 'RDM', 'Roberts Field')
INSERT INTO airports2 (570, 'OR', 'SLE', 'Salem Municipal Airport - McNary Field')
INSERT INTO airports2 (571, 'PA', 'ABE', 'Lehigh Valley International Airport')
INSERT INTO airports2 (572, 'PA', 'AOO', 'Altoona-Blair County Airport')
INSERT INTO airports2 (573, 'PA', 'AVP', 'Wilkes-Barre/Scranton International Airport')
INSERT INTO airports2 (574, 'PA', 'BFD', 'Bradford Regional Airport')
INSERT INTO airports2 (575, 'PA', 'DUJ', 'Du Bois-Jefferson County Airport')
INSERT INTO airports2 (576, 'PA', 'ERI', 'Erie International Airport')
INSERT INTO airports2 (577, 'PA', 'FKL', 'Venango Regional Airport')
INSERT INTO airports2 (578, 'PA', 'MDT', 'Harrisburg International Airport')
INSERT INTO airports2 (579, 'PA', 'JST', 'Johnstown-Cambria County Airport')
INSERT INTO airports2 (580, 'PA', 'LNS', 'Lancaster Airport')
INSERT INTO airports2 (581, 'PA', 'LBE', 'Arnold Palmer Regional Airport')
INSERT INTO airports2 (582, 'PA', 'PHL', 'Philadelphia International Airport')
INSERT INTO airports2 (583, 'PA', 'PIT', 'Pittsburgh International Airport')
INSERT INTO airports2 (584, 'PA', 'AGC', 'Allegheny County Airport')
INSERT INTO airports2 (585, 'PA', 'RDG', 'Reading Regional Airport')
INSERT INTO airports2 (586, 'PA', 'UNV', 'University Park Airport')
INSERT INTO airports2 (587, 'PA', 'IPT', 'Williamsport Regional Airport')
INSERT INTO airports2 (588, 'PR', 'BQN', 'Aguadilla Airport')
INSERT INTO airports2 (589, 'PR', 'X95', 'Diego Jimenez Torres Airport')
INSERT INTO airports2 (590, 'PR', 'CPX', 'Culebra Airport')
INSERT INTO airports2 (591, 'PR', 'VQS', 'Vieques Airport')
INSERT INTO airports2 (592, 'PR', 'MAZ', 'Mayaquez Airport')
INSERT INTO airports2 (593, 'PR', 'PSE', 'Mercedita Airport')
INSERT INTO airports2 (594, 'PR', 'SJU', 'Luis Munoz Marin International Airport')
INSERT INTO airports2 (595, 'PR', 'SIG', 'Fernando Luis Ribas Dominicci Airport')
INSERT INTO airports2 (596, 'RI', 'BID', 'Block Island State Airport')
INSERT INTO airports2 (597, 'RI', 'UUU', 'Newport State Airport')
INSERT INTO airports2 (598, 'RI', 'OQU', 'Quonset State Airport')
INSERT INTO airports2 (599, 'RI', 'SFZ', 'North Central State Airport')
INSERT INTO airports2 (600, 'RI', 'PVD', 'T.F. Green Airport')
INSERT INTO airports2 (601, 'RI', 'WST', 'Westerly State Airport')
INSERT INTO airports2 (602, 'SC', 'AND', 'Anderson Regional Airport')
INSERT INTO airports2 (603, 'SC', 'CHS', 'Charleston International Airport')
INSERT INTO airports2 (604, 'SC', 'CAE', 'Columbia Metropolitan Airport')
INSERT INTO airports2 (605, 'SC', 'FLO', 'Florence Regional Airport')
INSERT INTO airports2 (606, 'SC', 'GSP', 'Greenville / Spartanburg Airport')
INSERT INTO airports2 (607, 'SC', 'GYH', 'Donaldson Center Airport')
INSERT INTO airports2 (608, 'SC', 'HXD', 'Hilton Head Airport')
INSERT INTO airports2 (609, 'SC', 'MYR', 'Myrtle Beach Airport')
INSERT INTO airports2 (610, 'SD', 'ABR', 'Aberdeen Regional Airport')
INSERT INTO airports2 (611, 'SD', 'BKX', 'Brookings Municipal Airport')
INSERT INTO airports2 (612, 'SD', 'HON', 'Huron Regional Airport')
INSERT INTO airports2 (613, 'SD', 'MHE', 'Mitchell Municipal Airport')
INSERT INTO airports2 (614, 'SD', 'PIR', 'Pierre Regional Airport')
INSERT INTO airports2 (615, 'SD', 'RAP', 'Rapid City Regional Airport')
INSERT INTO airports2 (616, 'SD', 'FSD', 'Sioux Falls Regional Airport')
INSERT INTO airports2 (617, 'SD', 'ATY', 'Watertown Municipal Airport')
INSERT INTO airports2 (618, 'SD', 'YKN', 'Chan Gurney Municipal Airport')
INSERT INTO airports2 (619, 'TN', 'TRI', 'Tri-Cities Regional Airport')
INSERT INTO airports2 (620, 'TN', 'CHA', 'Chattanooga Metropolitan Airport')
INSERT INTO airports2 (621, 'TN', 'MKL', 'Mc Kellar-Sipes Regional Airport')
INSERT INTO airports2 (622, 'TN', 'TYS', 'Mcghee Tyson Airport')
INSERT INTO airports2 (623, 'TN', 'MEM', 'Memphis Airport')
INSERT INTO airports2 (624, 'TN', 'NQA', 'Millington Regional Jetport')
INSERT INTO airports2 (625, 'TN', 'BNA', 'Nashville International Airport')
INSERT INTO airports2 (626, 'TN', 'MQY', 'Smyrna Airport')
INSERT INTO airports2 (627, 'TX', 'ABI', 'Abilene Regional Airport')
INSERT INTO airports2 (628, 'TX', 'AMA', 'Amarillo International Airport')
INSERT INTO airports2 (629, 'TX', 'LBX', 'Brazoria County Airport')
INSERT INTO airports2 (630, 'TX', 'AUS', 'Austin-Bergstrom International Airport')
INSERT INTO airports2 (631, 'TX', 'BPT', 'Southeast Texas Regional Airport')
INSERT INTO airports2 (632, 'TX', 'BRO', 'Brownsville/South Padre Island International Airport')
INSERT INTO airports2 (633, 'TX', 'CLL', 'Easterwood Airport')
INSERT INTO airports2 (634, 'TX', 'CRP', 'Corpus Christi International Airport')
INSERT INTO airports2 (635, 'TX', 'DAL', 'Dallas Love Field')
INSERT INTO airports2 (636, 'TX', 'DFW', 'Dallas/Fort Worth International Airport')
INSERT INTO airports2 (637, 'TX', 'DRT', 'Del Rio International Airport')
INSERT INTO airports2 (638, 'TX', 'ELP', 'El Paso International Airport')
INSERT INTO airports2 (639, 'TX', 'GRK', 'Killeen-Fort Hood Regional Airport')
INSERT INTO airports2 (640, 'TX', 'FTW', 'Fort Worth Meacham International Airport')
INSERT INTO airports2 (641, 'TX', 'GLS', 'Galveston/Scholes International Airport')
INSERT INTO airports2 (642, 'TX', 'HRL', 'Valley International Airport')
INSERT INTO airports2 (643, 'TX', 'EFD', 'Ellington Field')
INSERT INTO airports2 (644, 'TX', 'HOU', 'Hobby Airport')
INSERT INTO airports2 (645, 'TX', 'IAH', 'Bush Intercontinental Airport')
INSERT INTO airports2 (646, 'TX', 'ILE', 'Skylark Field')
INSERT INTO airports2 (647, 'TX', 'LRD', 'Laredo International Airport')
INSERT INTO airports2 (648, 'TX', 'GGG', 'East Texas Regional Airport')
INSERT INTO airports2 (649, 'TX', 'LBB', 'Lubbock International Airport')
INSERT INTO airports2 (650, 'TX', 'MFE', 'Mcallen-Miller International Airport')
INSERT INTO airports2 (651, 'TX', 'MAF', 'Midland International Airport')
INSERT INTO airports2 (652, 'TX', 'SJT', 'San Angelo Regional Airport/Mathis Field')
INSERT INTO airports2 (653, 'TX', 'SAT', 'San Antonio International Airport')
INSERT INTO airports2 (654, 'TX', 'TPL', 'Draughon-Miller Central Texas Regional Airport')
INSERT INTO airports2 (655, 'TX', 'TYR', 'Tyler Pounds Regional Airport')
INSERT INTO airports2 (656, 'TX', 'VCT', 'Victoria Regional Airport')
INSERT INTO airports2 (657, 'TX', 'ACT', 'Waco Regional Airport')
INSERT INTO airports2 (658, 'TX', 'SPS', 'Wichita Falls Municipal Airport')
INSERT INTO airports2 (659, 'UT', 'BCE', 'Bryce Canyon Airport')
INSERT INTO airports2 (660, 'UT', 'CDC', 'Cedar City Regional Airport')
INSERT INTO airports2 (661, 'UT', 'CNY', 'Canyonlands Field')
INSERT INTO airports2 (662, 'UT', 'OGD', 'Ogden-Hinckley Airport')
INSERT INTO airports2 (663, 'UT', 'PVU', 'Provo Municipal Airport')
INSERT INTO airports2 (664, 'UT', 'SLC', 'Salt Lake City International Airport')
INSERT INTO airports2 (665, 'UT', 'SGU', 'St George Municipal Airport')
INSERT INTO airports2 (666, 'VA', 'CHO', 'Charlottesville-Albemarle Airport')
INSERT INTO airports2 (667, 'VA', 'DAN', 'Danville Regional Airport')
INSERT INTO airports2 (668, 'VA', 'SHD', 'Shenandoah Valley Regional Airport')
INSERT INTO airports2 (669, 'VA', 'LYH', 'Lynchburg Regional Airport/Preston Glenn Field')
INSERT INTO airports2 (670, 'VA', 'PHF', 'Newport News/Williamsburg International Airport')
INSERT INTO airports2 (671, 'VA', 'ORF', 'Norfolk International Airport')
INSERT INTO airports2 (672, 'VA', 'RIC', 'Richmond International Airport')
INSERT INTO airports2 (673, 'VA', 'ROA', 'Roanoke Regional Airport')
INSERT INTO airports2 (674, 'VI', 'STT', 'Cyril E King Airport')
INSERT INTO airports2 (675, 'VI', 'STX', 'Henry E Rohlsen Airport')
INSERT INTO airports2 (676, 'VT', 'MPV', 'Edward F. Knapp State Airport')
INSERT INTO airports2 (677, 'VT', 'DDH', 'William H. Morse State Airport')
INSERT INTO airports2 (678, 'VT', 'MVL', 'Morrisville-Stowe State Airport')
INSERT INTO airports2 (679, 'VT', 'EFK', 'Newport State Airport')
INSERT INTO airports2 (680, 'VT', 'RUT', 'Rutland State Airport')
INSERT INTO airports2 (681, 'VT', 'BTV', 'Burlington International Airport')
INSERT INTO airports2 (682, 'WA', '74S', 'Anacortes Airport')
INSERT INTO airports2 (683, 'WA', 'BLI', 'Bellingham International Airport')
INSERT INTO airports2 (684, 'WA', 'PWT', 'Bremerton National Airport')
INSERT INTO airports2 (685, 'WA', 'ORS', 'Orcas Island Airport')
INSERT INTO airports2 (686, 'WA', 'PAE', 'Snohomish County Airport (Paine Field)')
INSERT INTO airports2 (687, 'WA', 'FHR', 'Friday Harbor Airport')
INSERT INTO airports2 (688, 'WA', 'MWH', 'Grant County International Airport')
INSERT INTO airports2 (689, 'WA', 'OLM', 'Olympia Airport')
INSERT INTO airports2 (690, 'WA', 'PSC', 'Tri-Cities Airport')
INSERT INTO airports2 (691, 'WA', 'CLM', 'William R Fairchild International Airport')
INSERT INTO airports2 (692, 'WA', 'PUW', 'Pullman / Moscow Regional Airport')
INSERT INTO airports2 (693, 'WA', 'SEA', 'Seattle/Tacoma International Airport')
INSERT INTO airports2 (694, 'WA', 'BFI', 'Boeing Field/King County International Airport')
INSERT INTO airports2 (695, 'WA', 'GEG', 'Spokane International Airport')
INSERT INTO airports2 (696, 'WA', 'ALW', 'Walla Walla Regional Airport')
INSERT INTO airports2 (697, 'WA', 'EAT', 'Pangborn Memorial Airport')
INSERT INTO airports2 (698, 'WA', 'YKM', 'Yakima Air Terminal/Mcallister Field')
INSERT INTO airports2 (699, 'WI', 'ATW', 'Outagamie County Regional Airport')
INSERT INTO airports2 (700, 'WI', 'EAU', 'Chippewa Valley Regional Airport')
INSERT INTO airports2 (701, 'WI', 'GRB', 'Austin Straubel International Airport')
INSERT INTO airports2 (702, 'WI', 'JVL', 'Southern Wisconsin Regional Airport')
INSERT INTO airports2 (703, 'WI', 'ENW', 'Kenosha Regional Airport')
INSERT INTO airports2 (704, 'WI', 'LSE', 'La Crosse Municipal Airport')
INSERT INTO airports2 (705, 'WI', 'MSN', 'Dane County Regional Airport')
INSERT INTO airports2 (706, 'WI', 'MKE', 'General Mitchell International Airport')
INSERT INTO airports2 (707, 'WI', 'CWA', 'Central Wisconsin Airport')
INSERT INTO airports2 (708, 'WI', 'OSH', 'Wittman Regional Airport')
INSERT INTO airports2 (709, 'WI', 'RHI', 'Rhinelander-Oneida County Airport')
INSERT INTO airports2 (710, 'WV', 'BKW', 'Raleigh County Memorial Airport')
INSERT INTO airports2 (711, 'WV', 'CRW', 'Charleston Yeager Airport')
INSERT INTO airports2 (712, 'WV', 'CKB', 'Harrison/Marion Regional Airport')
INSERT INTO airports2 (713, 'WV', 'HTS', 'Tri-State Airport')
INSERT INTO airports2 (714, 'WV', 'LWB', 'Greenbrier Valley Airport')
INSERT INTO airports2 (715, 'WV', 'MGW', 'Morgantown Municipal Airport')
INSERT INTO airports2 (716, 'WV', 'PKB', 'Mid-Ohio Valley Regional Airport')
INSERT INTO airports2 (717, 'WY', 'CPR', 'Natrona County International Airport')
INSERT INTO airports2 (718, 'WY', 'CYS', 'Cheyenne Regional Airport')
INSERT INTO airports2 (719, 'WY', 'COD', 'Yellowstone Regional Airport')
INSERT INTO airports2 (720, 'WY', 'GCC', 'Gillette-Campbell County Airport')
INSERT INTO airports2 (721, 'WY', 'JAC', 'Jackson Hole Airport')
INSERT INTO airports2 (722, 'WY', 'LAR', 'Laramie Regional Airport')
INSERT INTO airports2 (723, 'WY', 'RIW', 'Riverton Regional Airport')
INSERT INTO airports2 (724, 'WY', 'RKS', 'Rock Springs-Sweetwater County Airport')
INSERT INTO airports2 (725, 'WY', 'SHR', 'Sheridan County Airport')
INSERT INTO airports2 (726, 'WY', 'WRL', 'Worland Municipal Airport')
EXIT
